// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaMxUaMxlqoeoz9tfi_8tIl9Rpvqfxajk',
    appId: '1:196481924074:web:310970f00f2907782b5093',
    messagingSenderId: '196481924074',
    projectId: 'gradegenius-7e268',
    authDomain: 'gradegenius-7e268.firebaseapp.com',
    storageBucket: 'gradegenius-7e268.firebasestorage.app',
    measurementId: 'G-QY74B5GYHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRBYPS5h8cTkc7QKeev8hVI9Qppj6-1U',
    appId: '1:196481924074:android:470823cfbf54548f2b5093',
    messagingSenderId: '196481924074',
    projectId: 'gradegenius-7e268',
    storageBucket: 'gradegenius-7e268.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaMxUaMxlqoeoz9tfi_8tIl9Rpvqfxajk',
    appId: '1:196481924074:web:4b4c9776c6715f6d2b5093',
    messagingSenderId: '196481924074',
    projectId: 'gradegenius-7e268',
    authDomain: 'gradegenius-7e268.firebaseapp.com',
    storageBucket: 'gradegenius-7e268.firebasestorage.app',
    measurementId: 'G-2QH1HWXCM4',
  );
}
